#pragma once

//typedef enum
//{
    //HUD_ELEMENT_NONE,
    //HUD_ELEMENT_AGENT_INVENTORY,
    //HUD_ELEMENT_AGENT_TOOLBELT,
    //HUD_ELEMENT_NANITE_INVENTORY,
    //HUD_ELEMENT_CRAFTING_BENCH,
//} HudElementType;
