dat = {   0: {   'active': False,
           'gravity': 0,
           'hud_img': -1,
           'hud_pos': -1,
           'infinite_texture': None,
           'infinite_texture_array': [],
           'infinite_texture_level': 0,
           'max_damage': 32,
           'name': 'empty_space',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': False,
           'solid': False,
           'texture_id': [-1, -1, -1, -1, -1, -1],
           'texture_order': [   [0, 1, 2, 3],
                                [0, 1, 2, 3],
                                [0, 1, 2, 3],
                                [0, 1, 2, 3],
                                [0, 1, 2, 3],
                                [0, 1, 2, 3]],
           'transparent': 0},
    1: {   'active': 1,
           'gravity': 0,
           'hud_img': 0,
           'hud_pos': 63,
           'infinite_texture': None,
           'infinite_texture_array': [],
           'infinite_texture_level': 0,
           'max_damage': 32,
           'name': 'test',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': True,
           'solid': True,
           'texture_id': [0, 0, 0, 0, 0, 0],
           'transparent': 0},
    2: {   'active': 1,
           'gravity': 0,
           'hud_img': 1,
           'hud_pos': 0,
           'infinite_texture': None,
           'infinite_texture_array': [],
           'infinite_texture_level': 0,
           'max_damage': 32,
           'name': 'stone',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': True,
           'solid': True,
           'texture_id': [1, 1, 1, 1, 1, 1],
           'transparent': 0},
    3: {   'active': 1,
           'gravity': 0,
           'hud_img': 2,
           'hud_pos': 1,
           'infinite_texture': None,
           'infinite_texture_array': [],
           'infinite_texture_level': 0,
           'max_damage': 32,
           'name': 'blue_ore',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': True,
           'solid': True,
           'texture_id': [2, 2, 2, 2, 2, 2],
           'transparent': 0},
    4: {   'active': 1,
           'gravity': 0,
           'hud_img': 3,
           'hud_pos': 2,
           'infinite_texture': None,
           'infinite_texture_array': [],
           'infinite_texture_level': 0,
           'max_damage': 32,
           'name': 'dirt',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': True,
           'solid': True,
           'texture_id': [3, 3, 3, 3, 3, 3],
           'transparent': 0},
    5: {   'active': 1,
           'gravity': 0,
           'hud_img': 4,
           'hud_pos': 3,
           'infinite_texture': None,
           'infinite_texture_array': [],
           'infinite_texture_level': 0,
           'max_damage': 32,
           'name': 'lava',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': True,
           'solid': True,
           'texture_id': [4, 4, 4, 4, 4, 4],
           'transparent': 0},
    6: {   'active': 1,
           'gravity': 0,
           'hud_img': 5,
           'hud_pos': 8,
           'infinite_texture': None,
           'infinite_texture_array': [],
           'infinite_texture_level': 0,
           'max_damage': 32,
           'name': 'sand_brick',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': True,
           'solid': True,
           'texture_id': [5, 5, 5, 5, 5, 5],
           'transparent': 0},
    7: {   'active': 1,
           'gravity': 0,
           'hud_img': 6,
           'hud_pos': 9,
           'infinite_texture': None,
           'infinite_texture_array': [],
           'infinite_texture_level': 0,
           'max_damage': 32,
           'name': 'sand_brick',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': True,
           'solid': True,
           'texture_id': [6, 6, 6, 6, 6, 6],
           'transparent': 0},
    8: {   'active': 1,
           'gravity': 0,
           'hud_img': 7,
           'hud_pos': 10,
           'infinite_texture': None,
           'infinite_texture_array': [],
           'infinite_texture_level': 0,
           'max_damage': 32,
           'name': 'grey_brick',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': True,
           'solid': True,
           'texture_id': [7, 7, 7, 7, 7, 7],
           'transparent': 0},
    9: {   'active': 1,
           'gravity': 0,
           'hud_img': 8,
           'hud_pos': 11,
           'infinite_texture': None,
           'infinite_texture_array': [],
           'infinite_texture_level': 0,
           'max_damage': 32,
           'name': 'sand',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': True,
           'solid': True,
           'texture_id': [8, 8, 8, 8, 8, 8],
           'transparent': 0},
    10: {   'active': 1,
            'gravity': 0,
            'hud_img': 9,
            'hud_pos': 16,
            'infinite_texture': None,
            'infinite_texture_array': [],
            'infinite_texture_level': 0,
            'max_damage': 32,
            'name': 'terminal',
            'neutron_tolerance': 2,
            'nuclear': 0,
            'occludes': True,
            'solid': True,
            'texture_id': [9, 9, 9, 9, 9, 9],
            'transparent': 0},
    11: {   'active': 1,
            'gravity': 0,
            'hud_img': 10,
            'hud_pos': 17,
            'infinite_texture': None,
            'infinite_texture_array': [],
            'infinite_texture_level': 0,
            'max_damage': 32,
            'name': 'tron',
            'neutron_tolerance': 2,
            'nuclear': 0,
            'occludes': True,
            'solid': True,
            'texture_id': [10, 10, 10, 10, 10, 10],
            'transparent': 0},
    12: {   'active': 1,
            'gravity': 0,
            'hud_img': 11,
            'hud_pos': 18,
            'infinite_texture': None,
            'infinite_texture_array': [],
            'infinite_texture_level': 0,
            'max_damage': 32,
            'name': 'battery',
            'neutron_tolerance': 2,
            'nuclear': 0,
            'occludes': True,
            'solid': True,
            'texture_id': [11, 12, 13, 13, 13, 13],
            'transparent': 0},
    13: {   'active': 1,
            'gravity': 0,
            'hud_img': 12,
            'hud_pos': 19,
            'infinite_texture': None,
            'infinite_texture_array': [],
            'infinite_texture_level': 0,
            'max_damage': 32,
            'name': 'solar_panel',
            'neutron_tolerance': 2,
            'nuclear': 0,
            'occludes': True,
            'solid': True,
            'texture_id': [14, 14, 14, 14, 14, 14],
            'transparent': 0},
    100: {   'active': 1,
             'gravity': 0,
             'hud_img': 13,
             'hud_pos': 32,
             'infinite_texture': None,
             'infinite_texture_array': [],
             'infinite_texture_level': 0,
             'max_damage': 32,
             'name': 'tree_bark_01',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': True,
             'solid': True,
             'texture_id': [15, 15, 16, 16, 16, 16],
             'transparent': 0},
    101: {   'active': 1,
             'gravity': 0,
             'hud_img': 14,
             'hud_pos': 33,
             'infinite_texture': None,
             'infinite_texture_array': [],
             'infinite_texture_level': 0,
             'max_damage': 32,
             'name': 'tree_bark_02',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': True,
             'solid': True,
             'texture_id': [17, 17, 18, 18, 18, 18],
             'transparent': 0},
    102: {   'active': 1,
             'gravity': 0,
             'hud_img': 15,
             'hud_pos': 34,
             'infinite_texture': None,
             'infinite_texture_array': [],
             'infinite_texture_level': 0,
             'max_damage': 32,
             'name': 'tree_bark_03',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': True,
             'solid': True,
             'texture_id': [15, 15, 19, 19, 19, 19],
             'transparent': 0},
    103: {   'active': 1,
             'gravity': 0,
             'hud_img': 16,
             'hud_pos': 35,
             'infinite_texture': None,
             'infinite_texture_array': [],
             'infinite_texture_level': 0,
             'max_damage': 32,
             'name': 'tree_bark_01',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': True,
             'solid': True,
             'texture_id': [17, 17, 20, 20, 20, 20],
             'transparent': 0}}
# buld name map
names = {}
for id,v in dat.items():
    name = v.get('name', None)
    if name is None:
        continue
    names[name] = id

