dat = {   0: {   'active': False,
           'gravity': 0,
           'hud_img': -1,
           'hud_pos': -1,
           'infinite_texture': None,
           'infinite_texture_array': [],
           'infinite_texture_level': 0,
           'max_damage': 32,
           'name': 'empty_space',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': False,
           'solid': False,
           'texture_id': [-1, -1, -1, -1, -1, -1],
           'texture_order': [   [0, 1, 2, 3],
                                [0, 1, 2, 3],
                                [0, 1, 2, 3],
                                [0, 1, 2, 3],
                                [0, 1, 2, 3],
                                [0, 1, 2, 3]],
           'transparent': 0},
    1: {   'active': 1,
           'gravity': 0,
           'hud_img': 0,
           'hud_pos': 63,
           'infinite_texture': None,
           'infinite_texture_array': [],
           'infinite_texture_level': 0,
           'max_damage': 32,
           'name': 'test',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': True,
           'solid': True,
           'texture_id': [0, 0, 0, 0, 0, 0],
           'transparent': 0},
    2: {   'active': 1,
           'gravity': 0,
           'hud_img': 1,
           'hud_pos': 0,
           'infinite_texture': None,
           'infinite_texture_array': [],
           'infinite_texture_level': 0,
           'max_damage': 32,
           'name': 'stone',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': True,
           'solid': True,
           'texture_id': [1, 1, 1, 1, 1, 1],
           'transparent': 0},
    3: {   'active': 1,
           'gravity': 0,
           'hud_img': 2,
           'hud_pos': 1,
           'infinite_texture': None,
           'infinite_texture_array': [],
           'infinite_texture_level': 0,
           'max_damage': 32,
           'name': 'lava',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': True,
           'solid': True,
           'texture_id': [2, 2, 2, 2, 2, 2],
           'transparent': 0},
    4: {   'active': 1,
           'gravity': 0,
           'hud_img': 3,
           'hud_pos': 2,
           'infinite_texture': None,
           'infinite_texture_array': [],
           'infinite_texture_level': 0,
           'max_damage': 32,
           'name': 'grass',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': True,
           'solid': True,
           'texture_id': [3, 4, 5, 5, 5, 5],
           'transparent': 0},
    5: {   'active': 1,
           'gravity': 0,
           'hud_img': 4,
           'hud_pos': 3,
           'infinite_texture': None,
           'infinite_texture_array': [],
           'infinite_texture_level': 0,
           'max_damage': 32,
           'name': 'dirt',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': True,
           'solid': True,
           'texture_id': [4, 4, 4, 4, 4, 4],
           'transparent': 0},
    6: {   'active': 1,
           'gravity': 0,
           'hud_img': 5,
           'hud_pos': 4,
           'infinite_texture': None,
           'infinite_texture_array': [],
           'infinite_texture_level': 0,
           'max_damage': 32,
           'name': 'blue_ore',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': True,
           'solid': True,
           'texture_id': [6, 6, 6, 6, 6, 6],
           'transparent': 0},
    8: {   'active': 1,
           'gravity': 0,
           'hud_img': 6,
           'hud_pos': 5,
           'infinite_texture': None,
           'infinite_texture_array': [],
           'infinite_texture_level': 0,
           'max_damage': 32,
           'name': 'sand_brick',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': True,
           'solid': True,
           'texture_id': [7, 7, 7, 7, 7, 7],
           'transparent': 0},
    9: {   'active': 1,
           'gravity': 0,
           'hud_img': 7,
           'hud_pos': 6,
           'infinite_texture': None,
           'infinite_texture_array': [],
           'infinite_texture_level': 0,
           'max_damage': 32,
           'name': 'sand_brick',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': True,
           'solid': True,
           'texture_id': [8, 8, 8, 8, 8, 8],
           'transparent': 0},
    10: {   'active': 1,
            'gravity': 0,
            'hud_img': 8,
            'hud_pos': 7,
            'infinite_texture': None,
            'infinite_texture_array': [],
            'infinite_texture_level': 0,
            'max_damage': 32,
            'name': 'grey_brick',
            'neutron_tolerance': 2,
            'nuclear': 0,
            'occludes': True,
            'solid': True,
            'texture_id': [9, 9, 9, 9, 9, 9],
            'transparent': 0},
    11: {   'active': 1,
            'gravity': 0,
            'hud_img': 9,
            'hud_pos': 8,
            'infinite_texture': None,
            'infinite_texture_array': [],
            'infinite_texture_level': 0,
            'max_damage': 32,
            'name': 'sand',
            'neutron_tolerance': 2,
            'nuclear': 0,
            'occludes': True,
            'solid': True,
            'texture_id': [10, 10, 10, 10, 10, 10],
            'transparent': 0},
    20: {   'active': 1,
            'gravity': 0,
            'hud_img': 10,
            'hud_pos': 16,
            'infinite_texture': 'water_01',
            'infinite_texture_array': [   11,
                                          12,
                                          13,
                                          14,
                                          15,
                                          16,
                                          17,
                                          18,
                                          19,
                                          20,
                                          21,
                                          22,
                                          23,
                                          24,
                                          25,
                                          26],
            'infinite_texture_level': 2,
            'max_damage': 32,
            'name': 'infinite_water_01',
            'neutron_tolerance': 2,
            'nuclear': 0,
            'occludes': True,
            'solid': True,
            'texture_id': [255, 255, 255, 255, 255, 255],
            'transparent': 0},
    21: {   'active': 1,
            'gravity': 0,
            'hud_img': 11,
            'hud_pos': 17,
            'infinite_texture': 'water_02',
            'infinite_texture_array': [   27,
                                          28,
                                          29,
                                          30,
                                          31,
                                          32,
                                          33,
                                          34,
                                          35,
                                          36,
                                          37,
                                          38,
                                          39,
                                          40,
                                          41,
                                          42],
            'infinite_texture_level': 2,
            'max_damage': 32,
            'name': 'infinite_water_02',
            'neutron_tolerance': 2,
            'nuclear': 0,
            'occludes': True,
            'solid': True,
            'texture_id': [255, 255, 255, 255, 255, 255],
            'transparent': 0},
    22: {   'active': 1,
            'gravity': 0,
            'hud_img': 12,
            'hud_pos': 18,
            'infinite_texture': 'sand_01',
            'infinite_texture_array': [   43,
                                          44,
                                          45,
                                          46,
                                          47,
                                          48,
                                          49,
                                          50,
                                          51,
                                          52,
                                          53,
                                          54,
                                          55,
                                          56,
                                          57,
                                          58],
            'infinite_texture_level': 2,
            'max_damage': 32,
            'name': 'infinite_sand_01',
            'neutron_tolerance': 2,
            'nuclear': 0,
            'occludes': True,
            'solid': True,
            'texture_id': [255, 255, 255, 255, 255, 255],
            'transparent': 0},
    23: {   'active': 1,
            'gravity': 0,
            'hud_img': 13,
            'hud_pos': 19,
            'infinite_texture': 'wood_01',
            'infinite_texture_array': [   59,
                                          60,
                                          61,
                                          62,
                                          63,
                                          64,
                                          65,
                                          66,
                                          67,
                                          68,
                                          69,
                                          70,
                                          71,
                                          72,
                                          73,
                                          74],
            'infinite_texture_level': 2,
            'max_damage': 32,
            'name': 'infinite_wood_01',
            'neutron_tolerance': 2,
            'nuclear': 0,
            'occludes': True,
            'solid': True,
            'texture_id': [255, 255, 255, 255, 255, 255],
            'transparent': 0},
    40: {   'active': 1,
            'gravity': 0,
            'hud_img': 14,
            'hud_pos': 32,
            'infinite_texture': None,
            'infinite_texture_array': [],
            'infinite_texture_level': 0,
            'max_damage': 32,
            'name': 'tree_top_01',
            'neutron_tolerance': 2,
            'nuclear': 0,
            'occludes': False,
            'solid': True,
            'texture_id': [75, 75, 75, 75, 75, 75],
            'transparent': 1},
    41: {   'active': 1,
            'gravity': 0,
            'hud_img': 15,
            'hud_pos': 33,
            'infinite_texture': None,
            'infinite_texture_array': [],
            'infinite_texture_level': 0,
            'max_damage': 32,
            'name': 'tree_top_02',
            'neutron_tolerance': 2,
            'nuclear': 0,
            'occludes': False,
            'solid': True,
            'texture_id': [76, 76, 76, 76, 76, 76],
            'transparent': 1},
    42: {   'active': 1,
            'gravity': 0,
            'hud_img': 16,
            'hud_pos': 34,
            'infinite_texture': None,
            'infinite_texture_array': [],
            'infinite_texture_level': 0,
            'max_damage': 32,
            'name': 'tree_top_03',
            'neutron_tolerance': 2,
            'nuclear': 0,
            'occludes': False,
            'solid': True,
            'texture_id': [77, 77, 77, 77, 77, 77],
            'transparent': 1},
    43: {   'active': 1,
            'gravity': 0,
            'hud_img': 17,
            'hud_pos': 35,
            'infinite_texture': None,
            'infinite_texture_array': [],
            'infinite_texture_level': 0,
            'max_damage': 32,
            'name': 'tree_top_04',
            'neutron_tolerance': 2,
            'nuclear': 0,
            'occludes': False,
            'solid': True,
            'texture_id': [78, 78, 78, 78, 78, 78],
            'transparent': 1},
    44: {   'active': 1,
            'gravity': 0,
            'hud_img': 18,
            'hud_pos': 36,
            'infinite_texture': None,
            'infinite_texture_array': [],
            'infinite_texture_level': 0,
            'max_damage': 32,
            'name': 'tree_bark_01',
            'neutron_tolerance': 2,
            'nuclear': 0,
            'occludes': True,
            'solid': True,
            'texture_id': [79, 79, 80, 80, 80, 80],
            'transparent': 0},
    45: {   'active': 1,
            'gravity': 0,
            'hud_img': 19,
            'hud_pos': 37,
            'infinite_texture': None,
            'infinite_texture_array': [],
            'infinite_texture_level': 0,
            'max_damage': 32,
            'name': 'tree_bark_02',
            'neutron_tolerance': 2,
            'nuclear': 0,
            'occludes': True,
            'solid': True,
            'texture_id': [81, 81, 82, 82, 82, 82],
            'transparent': 0},
    46: {   'active': 1,
            'gravity': 0,
            'hud_img': 20,
            'hud_pos': 38,
            'infinite_texture': None,
            'infinite_texture_array': [],
            'infinite_texture_level': 0,
            'max_damage': 32,
            'name': 'tree_bark_03',
            'neutron_tolerance': 2,
            'nuclear': 0,
            'occludes': True,
            'solid': True,
            'texture_id': [79, 79, 83, 83, 83, 83],
            'transparent': 0},
    47: {   'active': 1,
            'gravity': 0,
            'hud_img': 21,
            'hud_pos': 39,
            'infinite_texture': None,
            'infinite_texture_array': [],
            'infinite_texture_level': 0,
            'max_damage': 32,
            'name': 'tree_bark_01',
            'neutron_tolerance': 2,
            'nuclear': 0,
            'occludes': True,
            'solid': True,
            'texture_id': [81, 81, 84, 84, 84, 84],
            'transparent': 0},
    48: {   'active': 1,
            'gravity': 0,
            'hud_img': 20,
            'hud_pos': 40,
            'infinite_texture': None,
            'infinite_texture_array': [],
            'infinite_texture_level': 0,
            'max_damage': 32,
            'name': 'tree_bark2',
            'neutron_tolerance': 2,
            'nuclear': 0,
            'occludes': True,
            'solid': True,
            'texture_id': [81, 81, 83, 83, 83, 83],
            'transparent': 0},
    49: {   'active': 1,
            'gravity': 0,
            'hud_img': 22,
            'hud_pos': 41,
            'infinite_texture': None,
            'infinite_texture_array': [],
            'infinite_texture_level': 0,
            'max_damage': 32,
            'name': 'cherry_tree_bark',
            'neutron_tolerance': 2,
            'nuclear': 0,
            'occludes': True,
            'solid': True,
            'texture_id': [85, 85, 85, 85, 85, 85],
            'transparent': 0},
    50: {   'active': 1,
            'gravity': 0,
            'hud_img': 23,
            'hud_pos': 42,
            'infinite_texture': None,
            'infinite_texture_array': [],
            'infinite_texture_level': 0,
            'max_damage': 32,
            'name': 'cherry_tree_top',
            'neutron_tolerance': 2,
            'nuclear': 0,
            'occludes': False,
            'solid': True,
            'texture_id': [86, 86, 86, 86, 86, 86],
            'transparent': 1},
    100: {   'active': 1,
             'gravity': 0,
             'hud_img': 24,
             'hud_pos': 9,
             'infinite_texture': None,
             'infinite_texture_array': [],
             'infinite_texture_level': 0,
             'max_damage': 32,
             'name': 'terminal',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': True,
             'solid': True,
             'texture_id': [87, 87, 87, 87, 87, 87],
             'transparent': 0},
    101: {   'active': 1,
             'gravity': 0,
             'hud_img': 25,
             'hud_pos': 10,
             'infinite_texture': None,
             'infinite_texture_array': [],
             'infinite_texture_level': 0,
             'max_damage': 32,
             'name': 'tron',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': True,
             'solid': True,
             'texture_id': [88, 88, 88, 88, 88, 88],
             'transparent': 0},
    102: {   'active': 1,
             'gravity': 0,
             'hud_img': 26,
             'hud_pos': 11,
             'infinite_texture': None,
             'infinite_texture_array': [],
             'infinite_texture_level': 0,
             'max_damage': 32,
             'name': 'battery',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': True,
             'solid': True,
             'texture_id': [89, 90, 91, 91, 91, 91],
             'transparent': 0},
    103: {   'active': 1,
             'gravity': 0,
             'hud_img': 27,
             'hud_pos': 12,
             'infinite_texture': None,
             'infinite_texture_array': [],
             'infinite_texture_level': 0,
             'max_damage': 32,
             'name': 'solar_panel',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': True,
             'solid': True,
             'texture_id': [92, 92, 92, 92, 92, 92],
             'transparent': 0},
    164: {   'active': 1,
             'gravity': 0,
             'hud_img': 28,
             'hud_pos': 48,
             'infinite_texture': None,
             'infinite_texture_array': [],
             'infinite_texture_level': 0,
             'max_damage': 32,
             'name': 'tree_alt1',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': False,
             'solid': True,
             'texture_id': [93, 93, 93, 93, 93, 93],
             'transparent': 1},
    165: {   'active': 1,
             'gravity': 0,
             'hud_img': 28,
             'hud_pos': 49,
             'infinite_texture': None,
             'infinite_texture_array': [],
             'infinite_texture_level': 0,
             'max_damage': 32,
             'name': 'tree_alt2',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': False,
             'solid': True,
             'texture_id': [93, 93, 93, 93, 93, 93],
             'transparent': 2},
    166: {   'active': 1,
             'gravity': 0,
             'hud_img': 29,
             'hud_pos': 50,
             'infinite_texture': None,
             'infinite_texture_array': [],
             'infinite_texture_level': 0,
             'max_damage': 32,
             'name': 'leaves',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': False,
             'solid': True,
             'texture_id': [94, 94, 94, 94, 94, 94],
             'transparent': 2},
    167: {   'active': 1,
             'gravity': 0,
             'hud_img': 29,
             'hud_pos': 51,
             'infinite_texture': None,
             'infinite_texture_array': [],
             'infinite_texture_level': 0,
             'max_damage': 32,
             'name': 'leaves',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': False,
             'solid': True,
             'texture_id': [94, 94, 94, 94, 94, 94],
             'transparent': 3},
    168: {   'active': 1,
             'gravity': 0,
             'hud_img': 30,
             'hud_pos': 52,
             'infinite_texture': None,
             'infinite_texture_array': [],
             'infinite_texture_level': 0,
             'max_damage': 32,
             'name': 'leaves',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': False,
             'solid': True,
             'texture_id': [95, 95, 95, 95, 95, 95],
             'transparent': 2},
    169: {   'active': 1,
             'gravity': 0,
             'hud_img': 30,
             'hud_pos': 53,
             'infinite_texture': None,
             'infinite_texture_array': [],
             'infinite_texture_level': 0,
             'max_damage': 32,
             'name': 'leaves',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': False,
             'solid': True,
             'texture_id': [95, 95, 95, 95, 95, 95],
             'transparent': 3},
    170: {   'active': 1,
             'gravity': 0,
             'hud_img': 31,
             'hud_pos': 54,
             'infinite_texture': None,
             'infinite_texture_array': [],
             'infinite_texture_level': 0,
             'max_damage': 32,
             'name': 'leaves',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': False,
             'solid': True,
             'texture_id': [96, 96, 96, 96, 96, 96],
             'transparent': 2},
    171: {   'active': 1,
             'gravity': 0,
             'hud_img': 31,
             'hud_pos': 55,
             'infinite_texture': None,
             'infinite_texture_array': [],
             'infinite_texture_level': 0,
             'max_damage': 32,
             'name': 'leaves',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': False,
             'solid': True,
             'texture_id': [96, 96, 96, 96, 96, 96],
             'transparent': 3},
    174: {   'active': '2',
             'gravity': 0,
             'hud_img': 32,
             'hud_pos': 56,
             'infinite_texture': None,
             'infinite_texture_array': [],
             'infinite_texture_level': 0,
             'max_damage': 32,
             'name': 'wheat',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': False,
             'solid': True,
             'texture_id': [97, 97, 97, 97, 97, 97],
             'transparent': 2},
    175: {   'active': '2',
             'gravity': 0,
             'hud_img': 33,
             'hud_pos': 57,
             'infinite_texture': None,
             'infinite_texture_array': [],
             'infinite_texture_level': 0,
             'max_damage': 32,
             'name': 'corn',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': False,
             'solid': True,
             'texture_id': [98, 98, 98, 98, 98, 98],
             'transparent': 2},
    176: {   'active': '2',
             'gravity': 0,
             'hud_img': 34,
             'hud_pos': 58,
             'infinite_texture': None,
             'infinite_texture_array': [],
             'infinite_texture_level': 0,
             'max_damage': 32,
             'name': 'corn2',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': False,
             'solid': True,
             'texture_id': [99, 99, 99, 99, 99, 99],
             'transparent': 2},
    177: {   'active': '2',
             'gravity': 0,
             'hud_img': 35,
             'hud_pos': 59,
             'infinite_texture': None,
             'infinite_texture_array': [],
             'infinite_texture_level': 0,
             'max_damage': 32,
             'name': 'corn2',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': False,
             'solid': True,
             'texture_id': [100, 100, 100, 100, 100, 100],
             'transparent': 2},
    188: {   'active': '2',
             'gravity': 0,
             'hud_img': 36,
             'hud_pos': 60,
             'infinite_texture': None,
             'infinite_texture_array': [],
             'infinite_texture_level': 0,
             'max_damage': 32,
             'name': 'sunflower',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': False,
             'solid': True,
             'texture_id': [101, 101, 101, 101, 101, 101],
             'transparent': 2},
    189: {   'active': '2',
             'gravity': 0,
             'hud_img': 37,
             'hud_pos': 60,
             'infinite_texture': None,
             'infinite_texture_array': [],
             'infinite_texture_level': 0,
             'max_damage': 32,
             'name': 'sunflower_base',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': False,
             'solid': True,
             'texture_id': [102, 102, 102, 102, 102, 102],
             'transparent': 2},
    190: {   'active': '2',
             'gravity': 0,
             'hud_img': 38,
             'hud_pos': 61,
             'infinite_texture': None,
             'infinite_texture_array': [],
             'infinite_texture_level': 0,
             'max_damage': 32,
             'name': 'sunflower_top',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': False,
             'solid': True,
             'texture_id': [103, 103, 103, 103, 103, 103],
             'transparent': 2}}
