dat = {   0: {   'active': False,
           'gravity': 0,
           'hud_img': -1,
           'hud_pos': -1,
           'max_damage': 32,
           'name': 'empty_space',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': False,
           'solid': False,
           'texture_id': [-1, -1, -1, -1, -1, -1],
           'texture_order': [   [0, 1, 2, 3],
                                [0, 1, 2, 3],
                                [0, 1, 2, 3],
                                [0, 1, 2, 3],
                                [0, 1, 2, 3],
                                [0, 1, 2, 3]],
           'transparent': 0},
    1: {   'active': True,
           'gravity': 0,
           'hud_img': 0,
           'hud_pos': 3,
           'max_damage': 32,
           'name': 'test',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': True,
           'solid': True,
           'texture_id': [0, 0, 0, 0, 0, 0],
           'transparent': 0},
    2: {   'active': True,
           'gravity': 0,
           'hud_img': 1,
           'hud_pos': 2,
           'max_damage': 32,
           'name': 'stone',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': True,
           'solid': True,
           'texture_id': [1, 1, 1, 1, 1, 1],
           'transparent': 0},
    3: {   'active': True,
           'gravity': 0,
           'hud_img': 2,
           'hud_pos': 1,
           'max_damage': 32,
           'name': 'lava',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': True,
           'solid': True,
           'texture_id': [2, 2, 2, 2, 2, 2],
           'transparent': 0},
    4: {   'active': True,
           'gravity': 0,
           'hud_img': 3,
           'hud_pos': 4,
           'max_damage': 32,
           'name': 'grass',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': True,
           'solid': True,
           'texture_id': [4, 5, 3, 3, 3, 3],
           'transparent': 0},
    5: {   'active': True,
           'gravity': 0,
           'hud_img': -1,
           'hud_pos': -1,
           'max_damage': 32,
           'name': 'dirt',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': True,
           'solid': True,
           'texture_id': [5, 5, 5, 5, 5, 5],
           'transparent': 0},
    6: {   'active': True,
           'gravity': 0,
           'hud_img': -1,
           'hud_pos': -1,
           'max_damage': 32,
           'name': 'blue_ore',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': True,
           'solid': True,
           'texture_id': [6, 6, 6, 6, 6, 6],
           'transparent': 0},
    8: {   'active': True,
           'gravity': 0,
           'hud_img': -1,
           'hud_pos': -1,
           'max_damage': 32,
           'name': 'sand_brick',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': True,
           'solid': True,
           'texture_id': [7, 7, 7, 7, 7, 7],
           'transparent': 0},
    9: {   'active': True,
           'gravity': 0,
           'hud_img': -1,
           'hud_pos': -1,
           'max_damage': 32,
           'name': 'sand_brick',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': True,
           'solid': True,
           'texture_id': [8, 8, 8, 8, 8, 8],
           'transparent': 0},
    10: {   'active': True,
            'gravity': 0,
            'hud_img': -1,
            'hud_pos': -1,
            'max_damage': 32,
            'name': 'grey_brick',
            'neutron_tolerance': 2,
            'nuclear': 0,
            'occludes': True,
            'solid': True,
            'texture_id': [9, 9, 9, 9, 9, 9],
            'transparent': 0},
    11: {   'active': True,
            'gravity': 0,
            'hud_img': -1,
            'hud_pos': -1,
            'max_damage': 32,
            'name': 'sand',
            'neutron_tolerance': 2,
            'nuclear': 0,
            'occludes': True,
            'solid': True,
            'texture_id': [10, 10, 10, 10, 10, 10],
            'transparent': 0},
    100: {   'active': True,
             'gravity': 0,
             'hud_img': -1,
             'hud_pos': -1,
             'max_damage': 32,
             'name': 'terminal',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': True,
             'solid': True,
             'texture_id': [11, 11, 11, 11, 11, 11],
             'transparent': 0},
    101: {   'active': True,
             'gravity': 0,
             'hud_img': -1,
             'hud_pos': -1,
             'max_damage': 32,
             'name': 'tron',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': True,
             'solid': True,
             'texture_id': [12, 12, 12, 12, 12, 12],
             'transparent': 0}}
