dat = {   0: {   'active': False,
           'gravity': 0,
           'hud_img': -1,
           'hud_pos': -1,
           'max_damage': 32,
           'name': 'empty_space',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': False,
           'solid': False,
           'texture_id': [-1, -1, -1, -1, -1, -1],
           'texture_order': [   [0, 1, 2, 3],
                                [0, 1, 2, 3],
                                [0, 1, 2, 3],
                                [0, 1, 2, 3],
                                [0, 1, 2, 3],
                                [0, 1, 2, 3]],
           'transparent': 0},
    1: {   'active': 1,
           'gravity': 0,
           'hud_img': 0,
           'hud_pos': 63,
           'max_damage': 32,
           'name': 'test',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': 1,
           'solid': True,
           'texture_id': [0, 0, 0, 0, 0, 0],
           'transparent': 0},
    2: {   'active': 1,
           'gravity': 0,
           'hud_img': 1,
           'hud_pos': 0,
           'max_damage': 32,
           'name': 'stone',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': 1,
           'solid': True,
           'texture_id': [1, 1, 1, 1, 1, 1],
           'transparent': 0},
    3: {   'active': 1,
           'gravity': 0,
           'hud_img': 2,
           'hud_pos': 40,
           'max_damage': 32,
           'name': 'lava',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': 1,
           'solid': True,
           'texture_id': [2, 2, 2, 2, 2, 2],
           'transparent': 0},
    4: {   'active': 1,
           'gravity': 0,
           'hud_img': 3,
           'hud_pos': 8,
           'max_damage': 32,
           'name': 'grass',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': 1,
           'solid': True,
           'texture_id': [3, 4, 5, 5, 5, 5],
           'transparent': 0},
    5: {   'active': 1,
           'gravity': 0,
           'hud_img': 4,
           'hud_pos': 9,
           'max_damage': 32,
           'name': 'dirt',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': 1,
           'solid': True,
           'texture_id': [4, 4, 4, 4, 4, 4],
           'transparent': 0},
    6: {   'active': 1,
           'gravity': 0,
           'hud_img': 5,
           'hud_pos': 1,
           'max_damage': 32,
           'name': 'blue_ore',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': 1,
           'solid': True,
           'texture_id': [6, 6, 6, 6, 6, 6],
           'transparent': 0},
    8: {   'active': 1,
           'gravity': 0,
           'hud_img': 6,
           'hud_pos': 24,
           'max_damage': 32,
           'name': 'sand_brick',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': 1,
           'solid': True,
           'texture_id': [7, 7, 7, 7, 7, 7],
           'transparent': 0},
    9: {   'active': 1,
           'gravity': 0,
           'hud_img': 7,
           'hud_pos': 25,
           'max_damage': 32,
           'name': 'sand_brick',
           'neutron_tolerance': 2,
           'nuclear': 0,
           'occludes': 1,
           'solid': True,
           'texture_id': [8, 8, 8, 8, 8, 8],
           'transparent': 0},
    10: {   'active': 1,
            'gravity': 0,
            'hud_img': 8,
            'hud_pos': 26,
            'max_damage': 32,
            'name': 'grey_brick',
            'neutron_tolerance': 2,
            'nuclear': 0,
            'occludes': 1,
            'solid': True,
            'texture_id': [9, 9, 9, 9, 9, 9],
            'transparent': 0},
    11: {   'active': 1,
            'gravity': 0,
            'hud_img': 9,
            'hud_pos': 16,
            'max_damage': 32,
            'name': 'sand',
            'neutron_tolerance': 2,
            'nuclear': 0,
            'occludes': 1,
            'solid': True,
            'texture_id': [10, 10, 10, 10, 10, 10],
            'transparent': 0},
    16: {   'active': 1,
            'gravity': 0,
            'hud_img': 10,
            'hud_pos': 32,
            'max_damage': 32,
            'name': 'tree_alt',
            'neutron_tolerance': 2,
            'nuclear': 0,
            'occludes': 0,
            'solid': True,
            'texture_id': [11, 11, 11, 11, 11, 11],
            'transparent': 1},
    100: {   'active': 1,
             'gravity': 0,
             'hud_img': 11,
             'hud_pos': 40,
             'max_damage': 32,
             'name': 'terminal',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': 1,
             'solid': True,
             'texture_id': [12, 12, 12, 12, 12, 12],
             'transparent': 0},
    101: {   'active': 1,
             'gravity': 0,
             'hud_img': 12,
             'hud_pos': 41,
             'max_damage': 32,
             'name': 'tron',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': 1,
             'solid': True,
             'texture_id': [13, 13, 13, 13, 13, 13],
             'transparent': 0},
    150: {   'active': 1,
             'gravity': 0,
             'hud_img': -1,
             'hud_pos': -1,
             'max_damage': 32,
             'name': 'rock1',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': 1,
             'solid': True,
             'texture_id': [14, 14, 14, 14, 14, 14],
             'transparent': 0},
    151: {   'active': 1,
             'gravity': 0,
             'hud_img': -1,
             'hud_pos': -1,
             'max_damage': 32,
             'name': 'rock2',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': 1,
             'solid': True,
             'texture_id': [15, 15, 15, 15, 15, 15],
             'transparent': 0},
    164: {   'active': 1,
             'gravity': 0,
             'hud_img': 10,
             'hud_pos': 48,
             'max_damage': 32,
             'name': 'tree_alt1',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': 0,
             'solid': True,
             'texture_id': [11, 11, 11, 11, 11, 11],
             'transparent': 1},
    165: {   'active': 1,
             'gravity': 0,
             'hud_img': 10,
             'hud_pos': 49,
             'max_damage': 32,
             'name': 'tree_alt2',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': 0,
             'solid': True,
             'texture_id': [11, 11, 11, 11, 11, 11],
             'transparent': 2},
    166: {   'active': 1,
             'gravity': 0,
             'hud_img': 13,
             'hud_pos': 50,
             'max_damage': 32,
             'name': 'leaves',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': 0,
             'solid': True,
             'texture_id': [16, 16, 16, 16, 16, 16],
             'transparent': 2},
    167: {   'active': 1,
             'gravity': 0,
             'hud_img': 13,
             'hud_pos': 51,
             'max_damage': 32,
             'name': 'leaves',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': 0,
             'solid': True,
             'texture_id': [16, 16, 16, 16, 16, 16],
             'transparent': 3},
    168: {   'active': 1,
             'gravity': 0,
             'hud_img': 14,
             'hud_pos': 52,
             'max_damage': 32,
             'name': 'leaves',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': 0,
             'solid': True,
             'texture_id': [17, 17, 17, 17, 17, 17],
             'transparent': 2},
    169: {   'active': 1,
             'gravity': 0,
             'hud_img': 14,
             'hud_pos': 53,
             'max_damage': 32,
             'name': 'leaves',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': 0,
             'solid': True,
             'texture_id': [17, 17, 17, 17, 17, 17],
             'transparent': 3},
    170: {   'active': 1,
             'gravity': 0,
             'hud_img': 15,
             'hud_pos': 54,
             'max_damage': 32,
             'name': 'leaves',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': 0,
             'solid': True,
             'texture_id': [18, 18, 18, 18, 18, 18],
             'transparent': 2},
    171: {   'active': 1,
             'gravity': 0,
             'hud_img': 15,
             'hud_pos': 55,
             'max_damage': 32,
             'name': 'leaves',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': 0,
             'solid': True,
             'texture_id': [18, 18, 18, 18, 18, 18],
             'transparent': 3},
    172: {   'active': '2',
             'gravity': 0,
             'hud_img': 11,
             'hud_pos': 56,
             'max_damage': 32,
             'name': 'test2',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': 0,
             'solid': True,
             'texture_id': [12, 12, 12, 12, 12, 12],
             'transparent': 2},
    173: {   'active': '2',
             'gravity': 0,
             'hud_img': 255,
             'hud_pos': 57,
             'max_damage': 32,
             'name': 'test3',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': 0,
             'solid': True,
             'texture_id': [255, 255, 255, 255, 255, 255],
             'transparent': 3},
    174: {   'active': '2',
             'gravity': 0,
             'hud_img': 16,
             'hud_pos': 58,
             'max_damage': 32,
             'name': 'wheat',
             'neutron_tolerance': 2,
             'nuclear': 0,
             'occludes': 0,
             'solid': True,
             'texture_id': [19, 19, 19, 19, 19, 19],
             'transparent': 3}}
