#pragma once

int MAX_OBJECT_TYPES = 256;
typedef enum
{
    OBJECT_NONE = 0,    // null
    OBJECT_DESTINATION,     // abstract object

    OBJECT_AGENT,   // agent

    // projectiles
    OBJECT_GRENADE,

    // game items
    OBJECT_FLAG,
    OBJECT_BASE,

    // fabs
    OBJECT_AGENT_SPAWNER,
    OBJECT_TURRET,
    OBJECT_ENERGY_CORE,

    // mobs
    OBJECT_MONSTER_BOMB,
    OBJECT_MONSTER_BOX,
    OBJECT_MONSTER_SPAWNER,

    // inventories
    OBJECT_AGENT_INVENTORY,
    OBJECT_AGENT_TOOLBELT,
    OBJECT_SYNTHESIZER_INVENTORY,
    OBJECT_CRAFTING_BENCH,
    
} ObjectType;

int MAX_COMPONENT_TYPES = 256;
typedef enum
{
    COMPONENT_NONE,

    COMPONENT_POSITION,
    COMPONENT_POSITION_MOMENTUM,
    COMPONENT_POSITION_CHANGED,
    COMPONENT_POSITION_MOMENTUM_CHANGED,
    COMPONENT_VERLET,

    COMPONENT_STACKABLE,

    COMPONENT_PICKUP,

    COMPONENT_TTL,
    COMPONENT_HIT_POINTS,
    
    COMPONENT_VOXEL_MODEL,

    COMPONENT_OWNER,

    COMPONENT_AGENT_SPAWNER,
    COMPONENT_MONSTER_SPAWNER,

    COMPONENT_SPAWN_CHILD,
    
    COMPONENT_MOTION_TARGETING,
    COMPONENT_WEAPON_TARGETING,
    COMPONENT_DESTINATION_TARGETING,
    COMPONENT_AGENT_TARGETING,
    
    COMPONENT_STATE_MACHINE,
    COMPONENT_WAITING,
    
    COMPONENT_DIMENSION,

    COMPONENT_RATE_LIMIT,

    COMPONENT_HEALER,

    #if DC_CLIENT
    COMPONENT_BILLBOARD_SPRITE,
    COMPONENT_COLORED_VOXEL,
    COMPONENT_TEXTURED_VOXEL,

    COMPONENT_VOXEL_ANIMATION,
    COMPONENT_SPRITE_ANIMATION,
    #endif

    #if DC_SERVER
    COMPONENT_EXPLOSION,
    COMPONENT_ITEM_DROP,
    #endif
    
} ComponentType;

int MAX_COMPONENT_INTERFACE_TYPES = 256;
typedef enum
{
    COMPONENT_INTERFACE_NONE = 0,
    COMPONENT_INTERFACE_PHYSICS,    // physics state setters/getters
    COMPONENT_INTERFACE_STACKABLE,  // stackable setters/getters
    COMPONENT_INTERFACE_UPDATE,     // update()
    COMPONENT_INTERFACE_TICK,       // tick()
    COMPONENT_INTERFACE_PICKUP,
    COMPONENT_INTERFACE_HEALTH,     // is_dead()
    COMPONENT_INTERFACE_OWNER,      // owner getter/setter
    COMPONENT_INTERFACE_VOXEL_MODEL,
    COMPONENT_INTERFACE_SPAWNER,
    COMPONENT_INTERFACE_SPAWN_CHILD,
    COMPONENT_INTERFACE_TARGETING,
    COMPONENT_INTERFACE_DIMENSION,
    COMPONENT_INTERFACE_RATE_LIMIT,
    COMPONENT_INTERFACE_HEALING,
    COMPONENT_INTERFACE_STATE_MACHINE,
    COMPONENT_INTERFACE_WAITING,
    
    #if DC_CLIENT
    COMPONENT_INTERFACE_DRAW,       // draw()
    COMPONENT_INTERFACE_ANIMATION,
    #endif
    
    #if DC_SERVER
    COMPONENT_INTERFACE_EXPLOSION,
    COMPONENT_INTERFACE_ITEM_DROP,
    #endif
} ComponentInterfaceType;

typedef enum
{
    STATE_NONE,
    STATE_WAITING,
    STATE_IN_TRANSIT,
    STATE_CHASE_AGENT,
} EntityState;


#include <limits.h>
#include <physics/vec3.hpp>

const int NULL_ENTITY_ID = -1;      // cant use a positive number because it imposes constraint on all object list's max. dont send this over the network
const int NULL_OWNER = INT_MAX; // owners are ids of agents. they will never be INT_MAX
const int NULL_HEALTH = INT_MAX;
const Vec3 NULL_POSITION = vec3_init(0,0,0);
const Vec3 NULL_MOMENTUM = vec3_init(0,0,0);
const Vec3 NULL_ANGLES = vec3_init(0,0,0);
const float NULL_HEIGHT = 1.0f;
const int BASE_SPAWN_ID = -1;   // must use -1 because spawner max is unknown
