#pragma once

namespace t_hud
{

const int STACK_COUNT_MAX_LENGTH = 4;   // 9999

typedef enum
{
    UI_ELEMENT_NONE,
    UI_ELEMENT_AGENT_CONTAINER,
    UI_ELEMENT_AGENT_TOOLBELT,
    UI_ELEMENT_NANITE_CONTAINER,
    UI_ELEMENT_CRAFTING_CONTAINER,
    UI_ELEMENT_STORAGE_BLOCK,
} UIElementType;

} // t_hud
