dat = {
    0 : {
        'name': 'tile0',
        'occludes' : False,
        'active' : False,
        'solid' : False,
        'max_damage': 32,
        'neutron_tolerance' : 2,
        'nuclear': 0,
        'texture_id': [-1]*6,
        'texture_order': [[0,1,2,3]] * 6,
        'gravity'   :   0,
        'transparent': 0,
    },

    2 : {
            'name'  :   'tile2',
            'occludes': True,
            'active':   True,
            'solid':    True,
            'max_damage' : 32,
            'neutron_tolerance' : 2,
            'nuclear' : 0,
            'texture_id': [1]*6,
            'gravity'   :   0,
            'transparent': 0,
    },

    3 : {
            'name'  :   'tile2',
            'occludes': True,
            'active':   True,
            'solid':    True,
            'max_damage' : 32,
            'neutron_tolerance' : 2,
            'nuclear' : 0,
            'texture_id': [2]*6,
            'gravity'   :   0,
            'transparent': 0,
    },

    4 : {
            'name'  :   'tile2',
            'occludes': True,
            'active':   True,
            'solid':    True,
            'max_damage' : 32,
            'neutron_tolerance' : 2,
            'nuclear' : 0,
            'texture_id': [3]*6,
            'gravity'   :   0,
            'transparent': 0,
    },

    5 : {
            'name'  :   'tile2',
            'occludes': True,
            'active':   True,
            'solid':    True,
            'max_damage' : 32,
            'neutron_tolerance' : 2,
            'nuclear' : 0,
            'texture_id': [4]*6,
            'gravity'   :   0,
            'transparent': 0,
    },

    82 : {
            'name'  :   'tile2',
            'occludes': True,
            'active':   True,
            'solid':    True,
            'max_damage' : 32,
            'neutron_tolerance' : 2,
            'nuclear' : 0,
            'texture_id': [4]*6,
            'gravity'   :   0,
            'transparent': 0,
    },


}
